<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Demo.Share.Data</AssemblyName>
    <RootNamespace>Demo.Share.Data</RootNamespace>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Client\Demo\Assets\Demo\Scripts\Demo.Share.Data\**\*.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
    <ProjectReference Include="..\DE.Share.Data\DE.Share.Data.csproj" />
    <ProjectReference Include="..\DE.Share.DataTableSG\DE.Share.DataTableSG.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
