using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace DE.Share.DataTableSG
{
    internal static class SourceEmitter
    {
        private const string Data = "global::DE.Share.Data.";
        private const string Describe = Data + "DataDescribe.";
        private const string Provider = Data + "DataProvider.";
        internal const string FactoryName = "GeneratedFactory";

        public static string HintName(RowModel row)
        {
            var builder = new StringBuilder("DataTable_");
            foreach (char character in row.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            {
                builder.Append(((int)character).ToString("X4", CultureInfo.InvariantCulture));
            }
            return builder.Append(".g.cs").ToString();
        }

        public static string Emit(RowModel row)
        {
            var builder = new StringBuilder("// <auto-generated/>\n#nullable disable\n");
            bool hasNamespace = !row.Symbol.ContainingNamespace.IsGlobalNamespace;
            if (hasNamespace)
            {
                builder.Append("namespace ").Append(row.Symbol.ContainingNamespace.ToDisplayString()).Append("\n{\n");
            }
            var rowName = "@" + row.Symbol.Name;
            var rowType = row.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var tableName = "@" + row.TableTypeName;
            var dictionary = "global::System.Collections.Generic.Dictionary<" + Data + "DataTableKey, " + rowType + ">";
            builder.Append("    public sealed partial class ").Append(rowName).Append("\n    {\n")
                .Append("        internal static ").Append(rowType).Append(' ').Append(FactoryName)
                .Append('(').Append(Provider).Append("IDataTableReader reader)\n        {\n")
                .Append("            return new ").Append(rowType).Append("\n            {\n")
                .Append("                Id = ").Append(Data).Append("DataTableKey.FromInt32(reader.GetInt32(0))");
            for (int index = 0; index < row.Columns.Count; index++)
            {
                var column = row.Columns[index];
                var ordinal = (index + 1).ToString(CultureInfo.InvariantCulture);
                builder.Append(",\n                @").Append(column.PropertyName).Append(" = ");
                if (column.IsNullable)
                {
                    builder.Append("reader.IsNull(").Append(ordinal).Append(") ? (").Append(column.TypeName).Append("?)null : ");
                }
                builder.Append("reader.Get").Append(column.Kind);
                if (column.IsEnum)
                {
                    builder.Append('<').Append(column.TypeName).Append('>');
                }
                builder.Append('(').Append(ordinal).Append(')');
            }
            builder.Append("\n            };\n        }\n    }\n\n")
                .Append("    public sealed class ").Append(tableName).Append(" : ").Append(Data).Append("DataTable<").Append(rowType).Append(">\n    {\n")
                .Append("        public static readonly ").Append(Describe).Append("DataTableDescribe TableDescribe = new ").Append(Describe).Append("DataTableDescribe(\n")
                .Append("            ").Append(Literal(row.TableName)).Append(", ").Append(Literal(row.SourceName)).Append(", ").Append(Literal(row.SheetName)).Append(", ")
                .Append(Literal(row.Symbol.ToDisplayString(new SymbolDisplayFormat(typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces)))).Append(",\n")
                .Append("            new ").Append(Describe).Append("DataColumnDescribe(\"Id\", \"Id\", ").Append(Describe).Append("DataValueKind.Int32, isKey: true)");
            foreach (var column in row.Columns)
            {
                builder.Append(",\n            new ").Append(Describe).Append("DataColumnDescribe(")
                    .Append(Literal(column.PropertyName)).Append(", ").Append(Literal(column.ColumnName)).Append(", ")
                    .Append(Describe).Append("DataValueKind.").Append(column.Kind).Append(", isNullable: ").Append(column.IsNullable ? "true" : "false");
                if (column.IsEnum)
                {
                    builder.Append(", enumType: typeof(").Append(column.TypeName).Append(')');
                }
                builder.Append(')');
            }
            builder.Append(");\n\n        static ").Append(tableName).Append("()\n        {\n")
                .Append("            InitializeFactory(TableDescribe, Load);\n        }\n\n")
                .Append("        private ").Append(tableName).Append('(').Append(dictionary).Append(" rows) : base(TableDescribe, rows)\n        {\n        }\n\n")
                .Append("        private static ").Append(tableName).Append(" Load(").Append(Provider).Append("IDataProvider provider, string rootDirectory)\n        {\n")
                .Append("            return new ").Append(tableName).Append('(').Append(Data).Append("DataTableLoader.LoadRows(provider, rootDirectory, TableDescribe, ")
                .Append(rowType).Append('.').Append(FactoryName).Append("));\n        }\n    }\n");
            if (hasNamespace)
            {
                builder.Append("}\n");
            }
            return builder.ToString();
        }

        private static string Literal(string value)
        {
            return SymbolDisplay.FormatLiteral(value, true);
        }
    }
}
